ALTER TABLE public.albi_trail_registrations
ADD COLUMN IF NOT EXISTS chk_regolamento BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS chk_responsabilita BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS chk_privacy BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS chk_media BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS regolamento_version TEXT,
ADD COLUMN IF NOT EXISTS timestamp TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS user_agent TEXT,
ADD COLUMN IF NOT EXISTS ip_address TEXT;
